function [save_params] = create_save_params(...
  train_song_names,...
  validation_song_names,...
  test_song_names,...
  standardize_params,...
  run,...
  train_percentage,...
  left_frames_network,...
  right_frames_network,...
  is_chroma,...
  preprocessing_params,...)

save_params.train_song_names = train_song_names;
save_params.validation_song_names = validation_song_names;
save_params.test_song_names = test_song_names;
save_params.standardize_params = standardize_params;
save_params.run = run;
save_params.train_percentage = train_percentage;
save_params.left_frames_network = left_frames_network;
save_params.right_frames_network = right_frames_network;
save_params.is_chroma = is_chroma;
save_params.preprocessing_params = preprocessing_params;

end
