%function [ filename ] = save_sae(...
%    sae,...
%    sae_training_params,...
%    sae_network_params,...
%    train_sae_songs,...
%    train_sae_songs,...
%    test_nn_songs,...
%    nn,...
%    nn_training_params,...
%    error_rate,...
%    run,...
%    nn_train_percentage,...
%    sae_train_percentage,...
%    notes,...
%    preprocessing_params)
% 
% Saves a fully trained sae and neural network to be used
% and analyzed later.
%
% TODO(barapa): document the inputs

function [ filename ] = save_sae(...
    sae,...
    sae_training_params,...
    sae_network_params,...
    train_sae_songs,...
    test_nn_songs,...
    train_nn_songs,...
    nn,...
    nn_training_params,...
    error_rate,...
    run,...
    nn_train_percentage,...
    sae_train_percentage,...
    notes,...
    preprocessing_params)

save_dir = '/var/data/lenin/sae_models/';
ensure_dir_exists(save_dir);

filename = ['sae_', datestr(now, 'yyyymmddTHHMMSS')];
file_path = [save_dir, filename];

if ~exist('notes')
  notes = '';
end

if exist('preprocessing_params')
  save(file_path,...
      'sae',...
      'sae_training_params',...
      'sae_network_params',...
      'train_sae_songs',...
      'train_nn_songs',...
      'test_nn_songs',...
      'nn',...
      'nn_training_params',...
      'error_rate',...
      'run',...
      'nn_train_percentage',...
      'sae_train_percentage',...
      'notes',...
      'preprocessing_params');
else
  % HINT: we don't save 'preprocessing_params' here.
  save(file_path,...
      'sae',...
      'sae_training_params',...
      'sae_network_params',...
      'train_sae_songs',...
      'train_nn_songs',...
      'test_nn_songs',...
      'nn',...
      'nn_training_params',...
      'error_rate',...
      'run',...
      'nn_train_percentage',...
      'sae_train_percentage',...
      'notes');
end

filename = [filename '.mat'];

end

