function [ filename ] = save_shf_model(...
    scale_params,...
    theta,...
    results,...
    params,...
    run,...
    train_percentage,...
    train_file_names,...
    test_file_names,...
    notes)

save_dir = 'var/data/lenin/shf_models/';
ensure_dir_exists(save_dir);

filename = ['shf_', datestr(now, 'yyyymmddTHHMMSS')];
file_path = [save_dir, filename];

if ~exist('notes')
    notes = '';
end

save(file_path,...
    'scale_params',...
    'theta',...
    'results',...
    'params',...
    'run',...
    'train_percentage',...
    'train_file_names',...
    'test_file_names',...
    'notes');
end

